# SYSTEM MANAGED, DO NOT NOT EDIT, 
# Metadata for the project
title: "Modify HTTP response header"
tags: 
  - nodejs
  - starter
  - http
description: Blueprint for modifying response header implemented in NodeJS.
language:
  name: nodejs
  version: "20"
  title: NodeJS
version: 0.1.0
blueprint: true
handler: handler.js
section: 
  title: "Getting Started"
  slug: getting-started
