# SYSTEM MANAGED, DO NOT NOT EDIT, 
# Metadata for the project
title: "HTTP Redirect"
tags: 
  - golang
  - starter
  - http
description: Blueprint for returning HTTP redirect implemented in Golang.
language:
  name: python
  version: "3"
  title: Golang
version: 0.1.0
blueprint: true
handler: handler.go
section: 
  title: "Getting Started"
  slug: getting-started
