# SYSTEM MANAGED, DO NOT NOT EDIT,
# Metadata for the project
title: "Redis Connector"
tags:
  - connector
  - redis
  - nodejs
  - remote-ssh
description: The Redis connector enables seamless integration with any Redis database, allowing you to perform various operations efficiently.
language:
  name: nodejs
  version: "20"
  title: NodeJS
version: 0.1.0
blueprint: true
handler: handler.js
section:
  title: "Database Connectors"
  slug: database-connectors
  position: 3
envs:
  - name: MAX_CONNECTIONS
    description: Max connections to persist in the connection pool
    short_description: Connection pool size
    type: number
    default: "Enter connection pool size"
  - name: CONNECTION_TIMEOUT_MS
    description: Timeout for DB connections
    short_description: Timeout for DB connections
    type: number
    default: "Enter connection timeout"
icon: https://cdn.pixelbin.io/v2/fyndcloud/original/Temporal/Uploads/fcz0/undefined/images/ic_reddis_1714397917082.svg
activitySchema: |
  [
      {
          "name": "secret",
          "meta": {
              "displayName": "Redis Integration",
              "displayType": "autocomplete",
              "placeholder": "Select Redis Integration",
              "description": "Redis is a secure partner with Boltic. Your credentials are encrypted & can be removed at any time.",
              "options": [],
              "config": {
                  "urlType": "secret",
                  "method": "get",
                  "url": "/REDIS?current_page=1&page_size=999",
                  "labelKey": "name",
                  "valueKey": "_id"
              },
              "htmlProps": {
                  "showAddNew": true
              },
              "value": "",
              "validation": {
                  "required": true
              }
          }
      },
      {
          "name": "body",
          "meta": {
              "displayType": "object",
              "children": [
                  {
                      "name": "command",
                      "meta": {
                          "displayName": "Command",
                          "displayType": "code",
                          "placeholder": "GET/SET",
                          "description": "Please provide your command to run",
                          "validation": {
                              "required": true
                          },
                          "htmlProps": {
                              "fullscreen": true,
                              "language": "json",
                              "size": "md"
                          }
                      }
                  },
                  {
                      "name": "args",
                      "meta": {
                          "displayName": "Arguments",
                          "displayType": "code",
                          "placeholder": "KEY1 VALUE1",
                          "description": "Please provide your arguments for the command",
                          "validation": {
                              "required": true
                          },
                          "htmlProps": {
                              "fullscreen": true,
                              "language": "json",
                              "size": "md"
                          }
                      }
                  }
              ]
          }
      }
  ]
