# SYSTEM MANAGED, DO NOT NOT EDIT,
# Metadata for the project
title: "DNS Stats"
tags:
  - dns
  - python
description: Blueprint program to get DNS stats for the given domain
language:
  name: python
  version: "3"
  title: Python
version: 0.1.0
blueprint: true
handler: handler.py
section:
  title: "IT Automation"
  slug: it-automation
  position: 4
