# SYSTEM MANAGED, DO NOT NOT EDIT, 
# Metadata for the project
title: "Modify HTTP response header"
tags: 
  - python
  - starter
  - http
description: Blueprint for modifying response header implemented in Python.
language:
  name: python
  version: "3"
  title: Python
version: 0.1.0
blueprint: true
handler: handler.py
section: 
  title: "Getting Started"
  slug: getting-started
