# SYSTEM MANAGED, DO NOT NOT EDIT, 
# Metadata for the project
title: "Statelessness"
tags: 
  - golang
  - starter
  - http
description: An example of what variable state function instances do (and don't) store.
language:
  name: golang
  version: "1.22"
  title: Golang
version: 0.1.0
blueprint: true
handler: handler.go
section: 
  title: "IT Automation"
  slug: it-automation
  position: 3
