# SYSTEM MANAGED, DO NOT NOT EDIT, 
# Metadata for the project
title: "Hello world"
tags: 
  - python
  - starter
description: A starter serverless function 
language:
  name: python
  version: "3"
  title: Python
version: 0.1.0
blueprint: true
handler: handler.py
section: 
  title: "Getting Started"
  slug: getting-started
  position: 1
