# SYSTEM MANAGED, DO NOT NOT EDIT, 
# Metadata for the project
title: "Delayed execution"
tags: 
  - golang
  - timeout
description: Blueprint to delay request execution using timeouts
language:
  name: golang
  version: "1.22"
  title: Golang
version: 0.1.0
blueprint: true
handler: handler.go
section: 
  title: "Getting Started"
  slug: getting-started
  position: 1
