# SYSTEM MANAGED, DO NOT NOT EDIT,
# Metadata for the project
title: "HTTP connection pooling"
tags:
  - python
  - http
description: Shows how to recycle HTTP connections using HTTP connection pools.
language:
  name: python
  version: "3.12"
  title: Python
version: 0.1.0
blueprint: true
handler: handler.py
section:
  title: "External Integrations"
  slug: external-integrations
  position: 2
