# SYSTEM MANAGED, DO NOT NOT EDIT, 
# Metadata for the project
title: "OpenAI Integration"
tags: 
  - integration
  - openai
  - gpt
  - python
description: Integration with OpenAI's GPT API for generating conversational responses.
language:
  name: python
  version: "3"
  title: Python
version: 0.1.0
blueprint: true
handler: handler.py
section: 
  title: "External Integrations"
  slug: external-integrations
  position: 2
envs:
  OPENAI_API_KEY: "enter your key"
