# SYSTEM MANAGED, DO NOT NOT EDIT,
# Metadata for the project
title: "MongoDB Connector"
tags:
  - connector
  - mongo
  - mongodb
  - nodejs
  - remote-ssh
description: The MongoDB connector enables seamless integration with any MongoDB database, allowing you to perform various operations efficiently.
language:
  name: nodejs
  version: "20"
  title: NodeJS
version: 0.1.0
blueprint: true
handler: handler.js
section:
  title: "Database Connectors"
  slug: database-connectors
  position: 3
envs:
  - name: MAX_CONNECTIONS
    description: Max connections to persist in the connection pool
    short_description: Connection pool size
    type: number
    default: "Enter connection pool size"
  - name: CONNECTION_TIMEOUT_MS
    description: Timeout for DB connections
    short_description: Timeout for DB connections
    type: number
    default: "Enter connection timeout"
icon: "https://cdn.pixelbin.io/v2/fyndcloud/original/Temporal/Uploads/fcz0/c7d5096b-e8dd-4520-b1b9-0e4e01b839ab/images/png-transparent-mongodb-original-logo-icon-thumbnail_1733730330381.png"
activitySchema: |
  [
      {
          "name": "secret",
          "meta": {
              "displayName": "MongoDB Account",
              "displayType": "autocomplete",
              "placeholder": "Select MongoDB Account",
              "description": "MongoDB is a secure partner with Boltic. Your credentials are encrypted & can be removed at any time.",
              "options": [],
              "config": {
                  "urlType": "secret",
                  "method": "get",
                  "url": "/MONGODB?current_page=1&page_size=999",
                  "labelKey": "name",
                  "valueKey": "_id"
              },
              "htmlProps": {
                  "showAddNew": true
              },
              "value": "",
              "validation": {
                  "required": true
              }
          }
      },
      {
          "name": "body",
          "meta": {
              "displayType": "object",
              "children": [
                  {
                      "name": "query",
                      "meta": {
                          "displayName": "Query",
                          "displayType": "code",
                          "placeholder": "db.collection(\"example\").insertOne({ name: \"John Doe\", age: 30 })",
                          "description": "Please provide your query",
                          "validation": {
                              "required": true
                          },
                          "htmlProps": {
                              "fullscreen": true,
                              "language": "json",
                              "size": "md"
                          }
                      }
                  }
              ]
          }
      }
  ]
