# SYSTEM MANAGED, DO NOT NOT EDIT, 
# Metadata for the project
title: "Environment Variables"
tags: 
  - nodejs
description: Demonstrates how to use environment variables within a serverless function
language:
  name: nodejs
  version: "20"
  title: NodeJS
version: 0.1.0
blueprint: true
handler: handler.js
section: 
  title: "Getting Started"
  slug: getting-started
  position: 1
envs:
  - name: FOO
    description: Just a normal environment variable
    short_description: Environment variable
    type: string
    default: BAR
