# SYSTEM MANAGED, DO NOT NOT EDIT,
# Metadata for the project
title: "MySQL Connector"
tags:
  - connector
  - mysql
  - nodejs
  - remote-ssh
description: The MySQL connector enables seamless integration with any MySQL database, allowing you to perform various operations efficiently.
language:
  name: nodejs
  version: "20"
  title: NodeJS
version: 0.1.0
blueprint: true
handler: handler.js
section:
  title: "Database Connectors"
  slug: database-connectors
  position: 3
envs:
  - name: MAX_CONNECTIONS
    description: Max connections to persist in the connection pool
    short_description: Connection pool size
    type: number
    default: "Enter connection pool size"
  - name: CONNECTION_TIMEOUT_MS
    description: Timeout for DB connections
    short_description: Timeout for DB connections
    type: number
    default: "Enter connection timeout"
icon: https://cdn.pixelbin.io/v2/fyndcloud/original/Temporal/Uploads/bolt/undefined/images/mysql_1730110100059.png
activitySchema: |
  [
      {
          "name": "secret",
          "meta": {
              "displayName": "MySQL Integration",
              "displayType": "autocomplete",
              "placeholder": "Select MySQL Integration",
              "description": "MySQL is a secure partner with Boltic. Your credentials are encrypted & can be removed at any time.",
              "options": [],
              "config": {
                  "urlType": "secret",
                  "method": "get",
                  "url": "/MYSQL?current_page=1&page_size=999",
                  "labelKey": "name",
                  "valueKey": "_id"
              },
              "htmlProps": {
                  "showAddNew": true
              },
              "value": "",
              "validation": {
                  "required": true
              }
          }
      },
      {
          "name": "body",
          "meta": {
              "displayType": "object",
              "children": [
                  {
                      "name": "query",
                      "meta": {
                          "displayName": "Query",
                          "displayType": "code",
                          "placeholder": "SELECT * from example;",
                          "description": "Please provide your query",
                          "validation": {
                              "required": true
                          },
                          "htmlProps": {
                              "fullscreen": true,
                              "language": "sql",
                              "size": "md"
                          }
                      }
                  }
              ]
          }
      }
  ]
