# SYSTEM MANAGED, DO NOT NOT EDIT, 
# Metadata for the project
title: "HTTP Redirect"
tags: 
  - python
  - starter
  - http
description: Blueprint for returning HTTP redirect implemented in Python.
language:
  name: python
  version: "3"
  title: Python
version: 0.1.0
blueprint: true
handler: handler.py
section: 
  title: "Getting Started"
  slug: getting-started
